import Container from "../Container/Container";
import Cross from "../../assets/icons/cross.svg";
import aboutSml from "../../assets/images/about/about-sml.png";
import aboutSml2x from "../../assets/images/about/about-sml@2x.png";
import aboutMed from "../../assets/images/about/about-med.png";
import aboutMed2x from "../../assets/images/about/about-med@2x.png";
import aboutLrg from "../../assets/images/about/about-lrg.png";
import aboutLrg2x from "../../assets/images/about/about-lrg@2x.png";
import {
	TitleStyled,
	Wrapper,
	SecondWrapper,
	ThirdWrapper,
	Span,
	TextStyled,
	SecondTextStyled,
	ImageStyled,
	Icon,
} from "./About.styled";

const About = () => {
	return (
		<Container>
			<section id="about">
				<Wrapper>
					<TitleStyled>
						a Story that started with{" "}
						<Span>
							one simple <br /> ape
						</Span>{" "}
					</TitleStyled>
					<TextStyled>
						WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW
						THE IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT
					</TextStyled>
				</Wrapper>
				<SecondWrapper>
					<ThirdWrapper>
						<Icon
							src={Cross}
							alt="Cross icon"
						/>
						<SecondTextStyled>
							EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS
							ARE RANDOMLY GENERATED BY USERS
						</SecondTextStyled>
					</ThirdWrapper>
					<picture>
						<source
							srcSet={`${aboutSml} 1x, ${aboutSml2x} 2x`}
							media="(max-width: 767px)"
							type="image/jpeg"
						/>
						<source
							srcSet={`${aboutMed} 1x, ${aboutMed2x} 2x`}
							media="(min-width: 768px) and (max-width: 1279px)"
							type="image/jpeg"
						/>
						<source
							srcSet={`${aboutLrg} 1x, ${aboutLrg2x} 2x`}
							media="(min-width: 1280px)"
							type="image/jpeg"
						/>
						<ImageStyled src={aboutSml} alt="About Section Ape image" />
					</picture>
				</SecondWrapper>
			</section>
		</Container>
	);
};

export default About;
